# Generated by Django 3.2.7 on 2021-09-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('runtime', models.PositiveIntegerField()),
                ('genres', models.ManyToManyField(blank=True, related_name='genres', to='mrs.Genre')),
            ],
        ),
    ]
