# Generated by Django 3.2.7 on 2021-09-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0003_alter_movie_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='avg_rate',
            new_name='tot_rate',
        ),
        migrations.AddField(
            model_name='rating',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
