# Generated by Django 3.2.7 on 2021-09-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0005_rename_tot_rate_movie_avg_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='avg_rate',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
