# Generated by Django 3.2.7 on 2021-09-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0006_alter_movie_avg_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='voted',
        ),
    ]
