# Generated by Django 3.2.7 on 2021-09-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0007_remove_rating_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='mth',
            field=models.IntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], default=1),
            preserve_default=False,
        ),
    ]
