# Generated by Django 3.2.7 on 2021-09-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0012_alter_movie_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='img',
        ),
        migrations.AddField(
            model_name='movie',
            name='img_url',
            field=models.URLField(blank=True),
        ),
    ]
