# Generated by Django 3.2.7 on 2021-09-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0016_alter_movie_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=None),
        ),
    ]
