# Generated by Django 3.2.7 on 2021-09-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0017_alter_movie_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user_id',
            new_name='user',
        ),
    ]
