# Generated by Django 3.2.7 on 2021-09-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0018_auto_20210925_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='has_genre', to='mrs.Genre'),
        ),
    ]
