# Generated by Django 3.2.7 on 2021-09-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0020_alter_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='has_movies', to='mrs.Genre'),
        ),
    ]
