# Generated by Django 3.2.7 on 2021-09-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0021_alter_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='avg_rate',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
