# Generated by Django 3.2.7 on 2021-09-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0022_alter_movie_avg_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='avg_rate',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
